package com.d4rk.androidtutorials.constants.ui.lessons

object LessonCodeConstants {
    const val C = "C"
    const val CPP = "CPP"
    const val OBJECTIVEC = "ObjectiveC"
    const val CSHARP = "CSharp"
    const val JAVA = "Java"
    const val BASH = "Bash"
    const val PYTHON = "Python"
    const val PERL = "Perl"
    const val RUBY = "Ruby"
    const val JAVASCRIPT = "JavaScript"
    const val COFFEESCRIPT = "CoffeeScript"
    const val RUST = "Rust"
    const val BASIC = "Basic"
    const val CLOJURE = "Clojure"
    const val CSS = "CSS"
    const val DART = "Dart"
    const val ERLANG = "Erlang"
    const val GO = "Go"
    const val HASKELL = "Haskell"
    const val LISP = "Lisp"
    const val LUA = "Lua"
    const val MATLAB = "Matlab"
    const val ML = "ML"
    const val SML = "SML"
    const val MUMPS = "Mumps"
    const val PASCAL = "Pascal"
    const val SCALA = "Scala"
    const val SQL = "SQL"
    const val VHDL = "VHDL"
    const val TCL = "Tcl"
    const val WIKI = "Wiki"
    const val XQUERY = "XQuery"
    const val YAML = "YAML"
    const val MARKDOWN = "Markdown"
    const val JSON = "JSON"
    const val XML = "XML"
}